export const SIDEBAR_NAV_LABEL_SCHEMA = [
  { id: 'home', defaultLabel: 'Dashboard', sectionTitle: 'Principal' },
  { id: 'planos', defaultLabel: 'Planos', sectionTitle: 'Principal' },
  { id: 'concursos_disponiveis', defaultLabel: 'Objetivos', sectionTitle: 'Principal' },
  { id: 'lembretes', defaultLabel: 'Calendário', sectionTitle: 'Principal' },
  { id: 'disciplinas', defaultLabel: 'Disciplinas', sectionTitle: 'Principal' },
  { id: 'meus_concursos', defaultLabel: 'Meus objetivos', sectionTitle: 'Principal' },
  { id: 'edital', defaultLabel: 'Edital', sectionTitle: 'Estudos' },
  { id: 'edital_questao', defaultLabel: 'Edital em questão', sectionTitle: 'Estudos' },
  { id: 'planejamento', defaultLabel: 'Planejamento', sectionTitle: 'Estudos' },
  { id: 'ciclos', defaultLabel: 'Ciclos', sectionTitle: 'Estudos' },
  { id: 'metas_semana', defaultLabel: 'Metas da semana', sectionTitle: 'Estudos' },
  { id: 'sessoes', defaultLabel: 'Sessões', sectionTitle: 'Estudos' },
  { id: 'historico', defaultLabel: 'Histórico', sectionTitle: 'Estudos' },
  { id: 'estatisticas', defaultLabel: 'Estatísticas', sectionTitle: 'Estudos' },
  { id: 'questoes', defaultLabel: 'Questões', sectionTitle: 'Prática' },
  { id: 'simulados', defaultLabel: 'Simulados', sectionTitle: 'Prática' },
  { id: 'flashcards', defaultLabel: 'Flashcards', sectionTitle: 'Prática' },
  { id: 'revisoes', defaultLabel: 'Revisões', sectionTitle: 'Prática' },
  { id: 'redacoes', defaultLabel: 'Redações', sectionTitle: 'Prática' },
  { id: 'materiais', defaultLabel: 'Materiais', sectionTitle: 'Biblioteca' },
  { id: 'audiobooks', defaultLabel: 'Audiobooks', sectionTitle: 'Biblioteca' },
  { id: 'mapas_mentais', defaultLabel: 'Mapas mentais', sectionTitle: 'Biblioteca' },
  { id: 'legislacao', defaultLabel: 'Legislação', sectionTitle: 'Biblioteca' },
  { id: 'comunidades', defaultLabel: 'Comunidades', sectionTitle: 'Apoio' },
  { id: 'esquadroes', defaultLabel: 'Esquadrões', sectionTitle: 'Apoio' },
  { id: 'conciliador', defaultLabel: 'Conciliador', sectionTitle: 'Apoio' },
  { id: 'instagram', defaultLabel: 'Instagram', sectionTitle: 'Apoio' },
  { id: 'aplicativos', defaultLabel: 'Aplicativos', sectionTitle: 'Apoio' },
  { id: 'bem_estar', defaultLabel: 'Bem-estar', sectionTitle: 'Apoio' },
  { id: 'convide_ganhe', defaultLabel: 'Convide e ganhe', sectionTitle: 'Apoio' },
  { id: 'admin_dashboard', defaultLabel: 'Dashboard', sectionTitle: 'Admin' },
  { id: 'admin_concursos', defaultLabel: 'Catálogo', sectionTitle: 'Admin' },
  { id: 'admin_questoes', defaultLabel: 'Questões', sectionTitle: 'Admin' },
  { id: 'admin_disciplinas', defaultLabel: 'Disciplinas', sectionTitle: 'Admin' },
  { id: 'admin_usuarios', defaultLabel: 'Usuários', sectionTitle: 'Admin' },
  { id: 'admin_finance', defaultLabel: 'Financeiro', sectionTitle: 'Admin' },
  { id: 'admin_crm', defaultLabel: 'CRM', sectionTitle: 'Admin' },
  { id: 'admin_audiolivros', defaultLabel: 'Audiolivros', sectionTitle: 'Admin' },
  { id: 'admin_mapas_mentais', defaultLabel: 'Mapas mentais', sectionTitle: 'Admin' },
  { id: 'admin_legislacao', defaultLabel: 'Legislação', sectionTitle: 'Admin' },
  { id: 'admin_configuracoes', defaultLabel: 'Configurações', sectionTitle: 'Admin' },
];

export function getSidebarNavLabelSchema() {
  return SIDEBAR_NAV_LABEL_SCHEMA.map((item) => ({ ...item }));
}
