-- Import de rascunhos do catalogo (gerado por scripts/gen_catalog_drafts_sql.mjs)
-- 5 templates | por tipo: {"concurso":5} | pulados (ja existiam): 0
-- is_public=false (rascunho). Faculdades IGNORADAS de proposito.

with t as (
  insert into public.contest_templates (slug, nome, tipo, plano, concurso, area, cargo, banca, salario, inscricao_valor, escolaridade, vagas, lotacao, etapas, etapas_tags, taf_itens, cor, origem, status, is_public, descricao, imagem_url, edital_url, prova_data, status_concurso, conteudo_provisorio, conteudo_fonte_url)
  values ('camara-de-governador-valadares-administrador-2026', 'Câmara de Governador Valadares — Administrador 2026', 'concurso', 'Câmara de Governador Valadares — Administrador 2026', 'Câmara Municipal de Governador Valadares', 'Geral', 'Administrador', 'FGV', 'R$ 5.135,87', 'R$ 100,00', 'Superior completo', '1 + CR', 'Governador Valadares/MG', 'Prova objetiva e avaliação de títulos', '["objetiva","titulos"]'::jsonb, '[]'::jsonb, '#2563EB', 'catalogo', 'rascunho', false, 'Concurso da Câmara Municipal de Governador Valadares para Administrador, com vaga imediata e cadastro de reserva.', NULL, 'https://conhecimento.fgv.br/sites/default/files/concursos/edital-01-2026-abertura-do-concurso-publico-para-a-camara-municipal-de-governador-valadares_retificado_17_06_2026_0.pdf', '2026-11-22'::date, 'inscricoes_abertas', false, NULL)
  on conflict (slug) do nothing returning id
),
s as (
  insert into public.contest_template_subjects (template_id, nome, ordem)
  select t.id, d.nome, d.ordem from t cross join (values ('Língua Portuguesa', 0), ('Raciocínio Lógico Matemático', 1), ('Administração', 2)) as d(nome, ordem)
  returning id, nome
)
insert into public.contest_template_topics (subject_id, nome, ordem)
select s.id, tp.nome, tp.ordem from s join (values ('Língua Portuguesa', 'Interpretação e compreensão de texto', 0), ('Língua Portuguesa', 'Organização estrutural dos textos', 1), ('Língua Portuguesa', 'Coesão, coerência e intertextualidade', 2), ('Língua Portuguesa', 'Modos de organização discursiva', 3), ('Língua Portuguesa', 'Tipos textuais', 4), ('Língua Portuguesa', 'Tipologia da frase portuguesa', 5), ('Língua Portuguesa', 'Estrutura da frase portuguesa', 6), ('Língua Portuguesa', 'Tipos de discurso', 7), ('Língua Portuguesa', 'Registros de linguagem', 8), ('Língua Portuguesa', 'Elementos dos atos de comunicação', 9), ('Raciocínio Lógico Matemático', 'Proposições e valor-verdade', 0), ('Raciocínio Lógico Matemático', 'Equivalências lógicas', 1), ('Raciocínio Lógico Matemático', 'Problemas de raciocínio', 2), ('Raciocínio Lógico Matemático', 'Diagramas lógicos, tabelas e gráficos', 3), ('Raciocínio Lógico Matemático', 'Conjuntos e suas operações', 4), ('Raciocínio Lógico Matemático', 'Números naturais, inteiros, racionais e reais', 5), ('Raciocínio Lógico Matemático', 'Representação na reta', 6), ('Raciocínio Lógico Matemático', 'Unidades de medida', 7), ('Raciocínio Lógico Matemático', 'Plano cartesiano', 8), ('Raciocínio Lógico Matemático', 'Álgebra básica', 9), ('Administração', 'Introdução à Administração', 0), ('Administração', 'Funções administrativas', 1), ('Administração', 'Teorias da Administração', 2), ('Administração', 'Gestão por Competências', 3), ('Administração', 'Gestão de Projetos', 4), ('Administração', 'Estruturas organizacionais', 5), ('Administração', 'Planejamento estratégico', 6), ('Administração', 'Marketing e vendas', 7), ('Administração', 'Gestão financeira', 8), ('Administração', 'Recursos humanos', 9)) as tp(disc, nome, ordem) on tp.disc = s.nome;

with t as (
  insert into public.contest_templates (slug, nome, tipo, plano, concurso, area, cargo, banca, salario, inscricao_valor, escolaridade, vagas, lotacao, etapas, etapas_tags, taf_itens, cor, origem, status, is_public, descricao, imagem_url, edital_url, prova_data, status_concurso, conteudo_provisorio, conteudo_fonte_url)
  values ('camara-de-governador-valadares-comunicador-social-jornalista-2026', 'Câmara de Governador Valadares — Comunicador Social Jornalista 2026', 'concurso', 'Câmara de Governador Valadares — Comunicador Social Jornalista 2026', 'Câmara Municipal de Governador Valadares', 'Geral', 'Comunicador Social — Jornalista', 'FGV', 'R$ 5.135,87', 'R$ 100,00', 'Superior completo', '1 + CR', 'Governador Valadares/MG', 'Prova objetiva e avaliação de títulos', '["objetiva","titulos"]'::jsonb, '[]'::jsonb, '#2563EB', 'catalogo', 'rascunho', false, 'Concurso da Câmara Municipal de Governador Valadares para Comunicador Social — Jornalista, com vaga imediata e cadastro de reserva.', NULL, 'https://conhecimento.fgv.br/sites/default/files/concursos/edital-01-2026-abertura-do-concurso-publico-para-a-camara-municipal-de-governador-valadares_retificado_17_06_2026_0.pdf', '2026-11-22'::date, 'inscricoes_abertas', false, NULL)
  on conflict (slug) do nothing returning id
),
s as (
  insert into public.contest_template_subjects (template_id, nome, ordem)
  select t.id, d.nome, d.ordem from t cross join (values ('Língua Portuguesa', 0), ('Raciocínio Lógico Matemático', 1), ('Comunicação Social — Jornalismo', 2)) as d(nome, ordem)
  returning id, nome
)
insert into public.contest_template_topics (subject_id, nome, ordem)
select s.id, tp.nome, tp.ordem from s join (values ('Língua Portuguesa', 'Interpretação e compreensão de texto', 0), ('Língua Portuguesa', 'Organização estrutural dos textos', 1), ('Língua Portuguesa', 'Coesão, coerência e intertextualidade', 2), ('Língua Portuguesa', 'Modos de organização discursiva', 3), ('Língua Portuguesa', 'Tipos textuais', 4), ('Língua Portuguesa', 'Tipologia da frase portuguesa', 5), ('Língua Portuguesa', 'Estrutura da frase portuguesa', 6), ('Língua Portuguesa', 'Tipos de discurso', 7), ('Língua Portuguesa', 'Registros de linguagem', 8), ('Língua Portuguesa', 'Elementos dos atos de comunicação', 9), ('Raciocínio Lógico Matemático', 'Proposições e valor-verdade', 0), ('Raciocínio Lógico Matemático', 'Equivalências lógicas', 1), ('Raciocínio Lógico Matemático', 'Problemas de raciocínio', 2), ('Raciocínio Lógico Matemático', 'Diagramas lógicos, tabelas e gráficos', 3), ('Raciocínio Lógico Matemático', 'Conjuntos e suas operações', 4), ('Raciocínio Lógico Matemático', 'Números naturais, inteiros, racionais e reais', 5), ('Raciocínio Lógico Matemático', 'Representação na reta', 6), ('Raciocínio Lógico Matemático', 'Unidades de medida', 7), ('Raciocínio Lógico Matemático', 'Plano cartesiano', 8), ('Raciocínio Lógico Matemático', 'Álgebra básica', 9), ('Comunicação Social — Jornalismo', 'Teoria da comunicação', 0), ('Comunicação Social — Jornalismo', 'História da imprensa, rádio e televisão no Brasil', 1), ('Comunicação Social — Jornalismo', 'Legislação em comunicação social', 2), ('Comunicação Social — Jornalismo', 'Opinião pública', 3), ('Comunicação Social — Jornalismo', 'Gêneros de redação', 4), ('Comunicação Social — Jornalismo', 'Técnicas de redação jornalística', 5), ('Comunicação Social — Jornalismo', 'Processo gráfico', 6), ('Comunicação Social — Jornalismo', 'Planejamento editorial', 7), ('Comunicação Social — Jornalismo', 'Assessoria de imprensa', 8), ('Comunicação Social — Jornalismo', 'Comunicação empresarial', 9)) as tp(disc, nome, ordem) on tp.disc = s.nome;

with t as (
  insert into public.contest_templates (slug, nome, tipo, plano, concurso, area, cargo, banca, salario, inscricao_valor, escolaridade, vagas, lotacao, etapas, etapas_tags, taf_itens, cor, origem, status, is_public, descricao, imagem_url, edital_url, prova_data, status_concurso, conteudo_provisorio, conteudo_fonte_url)
  values ('camara-de-governador-valadares-contador-2026', 'Câmara de Governador Valadares — Contador 2026', 'concurso', 'Câmara de Governador Valadares — Contador 2026', 'Câmara Municipal de Governador Valadares', 'Fiscal', 'Contador', 'FGV', 'R$ 5.135,87', 'R$ 100,00', 'Superior completo', '1 + CR', 'Governador Valadares/MG', 'Prova objetiva e avaliação de títulos', '["objetiva","titulos"]'::jsonb, '[]'::jsonb, '#2563EB', 'catalogo', 'rascunho', false, 'Concurso da Câmara Municipal de Governador Valadares para Contador, com vaga imediata e cadastro de reserva.', NULL, 'https://conhecimento.fgv.br/sites/default/files/concursos/edital-01-2026-abertura-do-concurso-publico-para-a-camara-municipal-de-governador-valadares_retificado_17_06_2026_0.pdf', '2026-11-22'::date, 'inscricoes_abertas', false, NULL)
  on conflict (slug) do nothing returning id
),
s as (
  insert into public.contest_template_subjects (template_id, nome, ordem)
  select t.id, d.nome, d.ordem from t cross join (values ('Língua Portuguesa', 0), ('Raciocínio Lógico Matemático', 1), ('Contabilidade', 2)) as d(nome, ordem)
  returning id, nome
)
insert into public.contest_template_topics (subject_id, nome, ordem)
select s.id, tp.nome, tp.ordem from s join (values ('Língua Portuguesa', 'Interpretação e compreensão de texto', 0), ('Língua Portuguesa', 'Organização estrutural dos textos', 1), ('Língua Portuguesa', 'Coesão, coerência e intertextualidade', 2), ('Língua Portuguesa', 'Modos de organização discursiva', 3), ('Língua Portuguesa', 'Tipos textuais', 4), ('Língua Portuguesa', 'Tipologia da frase portuguesa', 5), ('Língua Portuguesa', 'Estrutura da frase portuguesa', 6), ('Língua Portuguesa', 'Tipos de discurso', 7), ('Língua Portuguesa', 'Registros de linguagem', 8), ('Língua Portuguesa', 'Elementos dos atos de comunicação', 9), ('Raciocínio Lógico Matemático', 'Proposições e valor-verdade', 0), ('Raciocínio Lógico Matemático', 'Equivalências lógicas', 1), ('Raciocínio Lógico Matemático', 'Problemas de raciocínio', 2), ('Raciocínio Lógico Matemático', 'Diagramas lógicos, tabelas e gráficos', 3), ('Raciocínio Lógico Matemático', 'Conjuntos e suas operações', 4), ('Raciocínio Lógico Matemático', 'Números naturais, inteiros, racionais e reais', 5), ('Raciocínio Lógico Matemático', 'Representação na reta', 6), ('Raciocínio Lógico Matemático', 'Unidades de medida', 7), ('Raciocínio Lógico Matemático', 'Plano cartesiano', 8), ('Raciocínio Lógico Matemático', 'Álgebra básica', 9), ('Contabilidade', 'Disponibilidades', 0), ('Contabilidade', 'Contas a receber', 1), ('Contabilidade', 'Estoques', 2), ('Contabilidade', 'Despesas antecipadas', 3), ('Contabilidade', 'Investimentos em coligadas e controladas', 4), ('Contabilidade', 'Goodwill', 5), ('Contabilidade', 'Passivo exigível', 6), ('Contabilidade', 'Fornecedores e obrigações fiscais', 7), ('Contabilidade', 'Empréstimos e financiamentos', 8), ('Contabilidade', 'Patrimônio líquido', 9)) as tp(disc, nome, ordem) on tp.disc = s.nome;

with t as (
  insert into public.contest_templates (slug, nome, tipo, plano, concurso, area, cargo, banca, salario, inscricao_valor, escolaridade, vagas, lotacao, etapas, etapas_tags, taf_itens, cor, origem, status, is_public, descricao, imagem_url, edital_url, prova_data, status_concurso, conteudo_provisorio, conteudo_fonte_url)
  values ('camara-de-governador-valadares-tecnico-superior-em-informatica-2026', 'Câmara de Governador Valadares — Técnico Superior em Informática 2026', 'concurso', 'Câmara de Governador Valadares — Técnico Superior em Informática 2026', 'Câmara Municipal de Governador Valadares', 'Geral', 'Técnico Superior em Informática', 'FGV', 'R$ 5.135,87', 'R$ 100,00', 'Superior completo', '1 + CR', 'Governador Valadares/MG', 'Prova objetiva e avaliação de títulos', '["objetiva","titulos"]'::jsonb, '[]'::jsonb, '#2563EB', 'catalogo', 'rascunho', false, 'Concurso da Câmara Municipal de Governador Valadares para Técnico Superior em Informática, com vaga imediata e cadastro de reserva.', NULL, 'https://conhecimento.fgv.br/sites/default/files/concursos/edital-01-2026-abertura-do-concurso-publico-para-a-camara-municipal-de-governador-valadares_retificado_17_06_2026_0.pdf', '2026-11-22'::date, 'inscricoes_abertas', false, NULL)
  on conflict (slug) do nothing returning id
),
s as (
  insert into public.contest_template_subjects (template_id, nome, ordem)
  select t.id, d.nome, d.ordem from t cross join (values ('Língua Portuguesa', 0), ('Raciocínio Lógico Matemático', 1), ('Segurança da Informação', 2)) as d(nome, ordem)
  returning id, nome
)
insert into public.contest_template_topics (subject_id, nome, ordem)
select s.id, tp.nome, tp.ordem from s join (values ('Língua Portuguesa', 'Interpretação e compreensão de texto', 0), ('Língua Portuguesa', 'Organização estrutural dos textos', 1), ('Língua Portuguesa', 'Coesão, coerência e intertextualidade', 2), ('Língua Portuguesa', 'Modos de organização discursiva', 3), ('Língua Portuguesa', 'Tipos textuais', 4), ('Língua Portuguesa', 'Tipologia da frase portuguesa', 5), ('Língua Portuguesa', 'Estrutura da frase portuguesa', 6), ('Língua Portuguesa', 'Tipos de discurso', 7), ('Língua Portuguesa', 'Registros de linguagem', 8), ('Língua Portuguesa', 'Elementos dos atos de comunicação', 9), ('Raciocínio Lógico Matemático', 'Proposições e valor-verdade', 0), ('Raciocínio Lógico Matemático', 'Equivalências lógicas', 1), ('Raciocínio Lógico Matemático', 'Problemas de raciocínio', 2), ('Raciocínio Lógico Matemático', 'Diagramas lógicos, tabelas e gráficos', 3), ('Raciocínio Lógico Matemático', 'Conjuntos e suas operações', 4), ('Raciocínio Lógico Matemático', 'Números naturais, inteiros, racionais e reais', 5), ('Raciocínio Lógico Matemático', 'Representação na reta', 6), ('Raciocínio Lógico Matemático', 'Unidades de medida', 7), ('Raciocínio Lógico Matemático', 'Plano cartesiano', 8), ('Raciocínio Lógico Matemático', 'Álgebra básica', 9), ('Segurança da Informação', 'Confidencialidade, integridade e disponibilidade', 0), ('Segurança da Informação', 'Classificação da informação', 1), ('Segurança da Informação', 'Gestão de ativos', 2), ('Segurança da Informação', 'ISO 27001 e ISO 27002', 3), ('Segurança da Informação', 'NIST Cybersecurity Framework', 4), ('Segurança da Informação', 'Lei Geral de Proteção de Dados (LGPD)', 5), ('Segurança da Informação', 'Criptografia', 6), ('Segurança da Informação', 'Controle de acesso', 7), ('Segurança da Informação', 'Firewalls, IDS/IPS, SIEM e SOC', 8), ('Segurança da Informação', 'Segurança em redes', 9)) as tp(disc, nome, ordem) on tp.disc = s.nome;

with t as (
  insert into public.contest_templates (slug, nome, tipo, plano, concurso, area, cargo, banca, salario, inscricao_valor, escolaridade, vagas, lotacao, etapas, etapas_tags, taf_itens, cor, origem, status, is_public, descricao, imagem_url, edital_url, prova_data, status_concurso, conteudo_provisorio, conteudo_fonte_url)
  values ('camara-de-governador-valadares-assistente-legislativo-2026', 'Câmara de Governador Valadares — Assistente Legislativo 2026', 'concurso', 'Câmara de Governador Valadares — Assistente Legislativo 2026', 'Câmara Municipal de Governador Valadares', 'Geral', 'Assistente Legislativo', 'FGV', 'R$ 4.108,68', 'R$ 70,00', 'Nível médio', '2 + CR', 'Governador Valadares/MG', 'Prova objetiva', '["objetiva"]'::jsonb, '[]'::jsonb, '#2563EB', 'catalogo', 'rascunho', false, 'Concurso da Câmara Municipal de Governador Valadares para Assistente Legislativo, com duas vagas imediatas e cadastro de reserva.', NULL, 'https://conhecimento.fgv.br/sites/default/files/concursos/edital-01-2026-abertura-do-concurso-publico-para-a-camara-municipal-de-governador-valadares_retificado_17_06_2026_0.pdf', '2026-11-22'::date, 'inscricoes_abertas', false, NULL)
  on conflict (slug) do nothing returning id
),
s as (
  insert into public.contest_template_subjects (template_id, nome, ordem)
  select t.id, d.nome, d.ordem from t cross join (values ('Língua Portuguesa', 0), ('Raciocínio Lógico Matemático', 1), ('Conhecimentos Específicos do Assistente Legislativo', 2)) as d(nome, ordem)
  returning id, nome
)
insert into public.contest_template_topics (subject_id, nome, ordem)
select s.id, tp.nome, tp.ordem from s join (values ('Língua Portuguesa', 'Interpretação de textos argumentativos', 0), ('Língua Portuguesa', 'Processos de construção textual', 1), ('Língua Portuguesa', 'Progressão textual', 2), ('Língua Portuguesa', 'Coesão, coerência e intertextualidade', 3), ('Língua Portuguesa', 'Reescritura de frases', 4), ('Língua Portuguesa', 'Domínio vocabular', 5), ('Língua Portuguesa', 'Estrangeirismos', 6), ('Língua Portuguesa', 'Classes de palavras', 7), ('Língua Portuguesa', 'Organização sintática e pontuação', 8), ('Língua Portuguesa', 'Variação linguística', 9), ('Raciocínio Lógico Matemático', 'Proposições e valor-verdade', 0), ('Raciocínio Lógico Matemático', 'Equivalências lógicas', 1), ('Raciocínio Lógico Matemático', 'Problemas de raciocínio', 2), ('Raciocínio Lógico Matemático', 'Diagramas lógicos, tabelas e gráficos', 3), ('Raciocínio Lógico Matemático', 'Conjuntos e suas operações', 4), ('Raciocínio Lógico Matemático', 'Números naturais, inteiros, racionais e reais', 5), ('Raciocínio Lógico Matemático', 'Representação na reta', 6), ('Raciocínio Lógico Matemático', 'Unidades de medida', 7), ('Raciocínio Lógico Matemático', 'Plano cartesiano', 8), ('Raciocínio Lógico Matemático', 'Álgebra básica', 9), ('Conhecimentos Específicos do Assistente Legislativo', 'Planejamento, organização, direção e controle', 0), ('Conhecimentos Específicos do Assistente Legislativo', 'Atendimento ao público', 1), ('Conhecimentos Específicos do Assistente Legislativo', 'Organização e gestão de documentos', 2), ('Conhecimentos Específicos do Assistente Legislativo', 'Gestão de materiais e patrimônio', 3), ('Conhecimentos Específicos do Assistente Legislativo', 'Gestão de recursos humanos', 4), ('Conhecimentos Específicos do Assistente Legislativo', 'Administração financeira', 5), ('Conhecimentos Específicos do Assistente Legislativo', 'Organização do ambiente de trabalho', 6), ('Conhecimentos Específicos do Assistente Legislativo', 'Redação oficial', 7), ('Conhecimentos Específicos do Assistente Legislativo', 'Serviços públicos', 8), ('Conhecimentos Específicos do Assistente Legislativo', 'Atos e contratos administrativos', 9)) as tp(disc, nome, ordem) on tp.disc = s.nome;
