-- Import de rascunhos do catalogo (gerado por scripts/gen_catalog_drafts_sql.mjs)
-- 3 templates | por tipo: {"concurso":3} | pulados (ja existiam): 0
-- is_public=false (rascunho). Faculdades IGNORADAS de proposito.

with t as (
  insert into public.contest_templates (slug, nome, tipo, plano, concurso, area, cargo, banca, salario, inscricao_valor, escolaridade, vagas, lotacao, etapas, etapas_tags, taf_itens, cor, origem, status, is_public, descricao, imagem_url, edital_url, prova_data, status_concurso, conteudo_provisorio, conteudo_fonte_url)
  values ('pcpr-delegado-de-policia-2026', 'PCPR — Delegado de Polícia 2026', 'concurso', 'PCPR — Delegado de Polícia 2026', 'Polícia Civil do Paraná', 'Policial', 'Delegado de Polícia', 'FGV', 'R$ 26.876,48', 'R$ 242,47', 'Bacharelado em Direito e três anos de atividade jurídica ou policial', 'CR', 'Paraná', 'Prova objetiva, provas discursivas e oral, prova de títulos, exame pré-admissional, TAF, avaliação psicológica e investigação social', '["objetiva","discursiva","oral","titulos","taf","psicotecnico","investigacao_social","medico"]'::jsonb, '["Flexão de braços em barra fixa","Flexão abdominal remador","Shuttle Run","Escalada em corda","Corrida de resistência em 12 minutos"]'::jsonb, '#2563EB', 'catalogo', 'rascunho', false, 'Concurso da Polícia Civil do Paraná para Delegado de Polícia, com etapas escritas, oral, físicas e investigação social.', NULL, 'https://conhecimento.fgv.br/sites/default/files/concursos/edital-01-2026-pcpr-publicacao.docx-1.pdf', '2026-10-11'::date, 'inscricoes_abertas', false, NULL)
  on conflict (slug) do nothing returning id
),
s as (
  insert into public.contest_template_subjects (template_id, nome, ordem)
  select t.id, d.nome, d.ordem from t cross join (values ('Direito Penal', 0), ('Ciências Forenses', 1), ('Criminologia', 2)) as d(nome, ordem)
  returning id, nome
)
insert into public.contest_template_topics (subject_id, nome, ordem)
select s.id, tp.nome, tp.ordem from s join (values ('Direito Penal', 'Princípios fundamentais do Direito Penal', 0), ('Direito Penal', 'Aplicação da lei penal no tempo', 1), ('Direito Penal', 'Aplicação da lei penal no espaço', 2), ('Direito Penal', 'Teoria geral do crime', 3), ('Direito Penal', 'Dolo e culpa', 4), ('Direito Penal', 'Ilicitude', 5), ('Direito Penal', 'Culpabilidade', 6), ('Direito Penal', 'Concurso de pessoas', 7), ('Direito Penal', 'Teoria da pena', 8), ('Direito Penal', 'Extinção da punibilidade', 9), ('Direito Penal', 'Crimes contra a pessoa', 10), ('Direito Penal', 'Crimes contra o patrimônio', 11), ('Ciências Forenses', 'Medicina Legal', 0), ('Ciências Forenses', 'Perícia médico-legal', 1), ('Ciências Forenses', 'Antropologia Forense', 2), ('Ciências Forenses', 'Identificação humana', 3), ('Ciências Forenses', 'Papiloscopia', 4), ('Ciências Forenses', 'Odontologia legal', 5), ('Ciências Forenses', 'Identificação por DNA', 6), ('Ciências Forenses', 'Reconhecimento facial automatizado', 7), ('Ciências Forenses', 'Sexologia Forense', 8), ('Ciências Forenses', 'Traumatologia Forense', 9), ('Ciências Forenses', 'Balística forense', 10), ('Ciências Forenses', 'Tanatologia Forense', 11), ('Ciências Forenses', 'Toxicologia Forense', 12), ('Criminologia', 'Conceito e objeto da Criminologia', 0), ('Criminologia', 'Método da Criminologia', 1), ('Criminologia', 'Criminologia crítica', 2), ('Criminologia', 'Criminologia positivista', 3), ('Criminologia', 'Escola clássica', 4), ('Criminologia', 'Escola positiva', 5), ('Criminologia', 'Teorias do etiquetamento', 6), ('Criminologia', 'Vitimologia', 7), ('Criminologia', 'Controle social do crime', 8), ('Criminologia', 'Política criminal', 9), ('Criminologia', 'Perfil criminal', 10), ('Criminologia', 'Criminologia digital', 11)) as tp(disc, nome, ordem) on tp.disc = s.nome;

with t as (
  insert into public.contest_templates (slug, nome, tipo, plano, concurso, area, cargo, banca, salario, inscricao_valor, escolaridade, vagas, lotacao, etapas, etapas_tags, taf_itens, cor, origem, status, is_public, descricao, imagem_url, edital_url, prova_data, status_concurso, conteudo_provisorio, conteudo_fonte_url)
  values ('pcpr-agente-de-policia-judiciaria-2026', 'PCPR — Agente de Polícia Judiciária 2026', 'concurso', 'PCPR — Agente de Polícia Judiciária 2026', 'Polícia Civil do Paraná', 'Policial', 'Agente de Polícia Judiciária', 'FGV', 'R$ 9.007,67', 'R$ 156,36', 'Curso superior completo', 'CR', 'Paraná', 'Prova objetiva, exame pré-admissional, TAF, avaliação psicológica, investigação social e prova de títulos', '["objetiva","titulos","taf","psicotecnico","investigacao_social","medico"]'::jsonb, '["Flexão de braços em barra fixa","Flexão abdominal remador","Shuttle Run","Escalada em corda","Corrida de resistência em 12 minutos"]'::jsonb, '#2563EB', 'catalogo', 'rascunho', false, 'Concurso da Polícia Civil do Paraná para Agente de Polícia Judiciária, com prova objetiva e etapas físicas e de investigação.', NULL, 'https://conhecimento.fgv.br/sites/default/files/concursos/edital-01-2026-pcpr-publicacao.docx-1.pdf', '2026-10-11'::date, 'inscricoes_abertas', false, NULL)
  on conflict (slug) do nothing returning id
),
s as (
  insert into public.contest_template_subjects (template_id, nome, ordem)
  select t.id, d.nome, d.ordem from t cross join (values ('Língua Portuguesa', 0), ('Raciocínio Lógico-Matemático', 1), ('Tecnologia e Sistemas de Informação e de Comunicação, Segurança Cibernética e Crimes Digitais', 2)) as d(nome, ordem)
  returning id, nome
)
insert into public.contest_template_topics (subject_id, nome, ordem)
select s.id, tp.nome, tp.ordem from s join (values ('Língua Portuguesa', 'Compreensão e interpretação de textos', 0), ('Língua Portuguesa', 'Estrutura textual', 1), ('Língua Portuguesa', 'Coerência textual', 2), ('Língua Portuguesa', 'Organização do discurso', 3), ('Língua Portuguesa', 'Tipos textuais', 4), ('Língua Portuguesa', 'Textos literários e não literários', 5), ('Língua Portuguesa', 'Tipologia de frases', 6), ('Língua Portuguesa', 'Estrutura da oração', 7), ('Língua Portuguesa', 'Pontuação', 8), ('Língua Portuguesa', 'Sintaxe', 9), ('Língua Portuguesa', 'Ordem direta e inversa', 10), ('Língua Portuguesa', 'Registros de linguagem', 11), ('Raciocínio Lógico-Matemático', 'Lógica proposicional', 0), ('Raciocínio Lógico-Matemático', 'Conectivos e equivalências lógicas', 1), ('Raciocínio Lógico-Matemático', 'Teoria dos conjuntos', 2), ('Raciocínio Lógico-Matemático', 'Conjuntos numéricos', 3), ('Raciocínio Lógico-Matemático', 'Razões e proporções', 4), ('Raciocínio Lógico-Matemático', 'Grandezas e medidas', 5), ('Raciocínio Lógico-Matemático', 'Estruturas lógicas', 6), ('Raciocínio Lógico-Matemático', 'Tabelas e gráficos', 7), ('Raciocínio Lógico-Matemático', 'Análise combinatória', 8), ('Raciocínio Lógico-Matemático', 'Probabilidade', 9), ('Raciocínio Lógico-Matemático', 'Geometria', 10), ('Raciocínio Lógico-Matemático', 'Plano cartesiano', 11), ('Tecnologia e Sistemas de Informação e de Comunicação, Segurança Cibernética e Crimes Digitais', 'Hardware e software', 0), ('Tecnologia e Sistemas de Informação e de Comunicação, Segurança Cibernética e Crimes Digitais', 'Armazenamento e backup', 1), ('Tecnologia e Sistemas de Informação e de Comunicação, Segurança Cibernética e Crimes Digitais', 'Windows, Android e iOS', 2), ('Tecnologia e Sistemas de Informação e de Comunicação, Segurança Cibernética e Crimes Digitais', 'Computação em nuvem', 3), ('Tecnologia e Sistemas de Informação e de Comunicação, Segurança Cibernética e Crimes Digitais', 'Redes de computadores', 4), ('Tecnologia e Sistemas de Informação e de Comunicação, Segurança Cibernética e Crimes Digitais', 'IP, DNS e VPN', 5), ('Tecnologia e Sistemas de Informação e de Comunicação, Segurança Cibernética e Crimes Digitais', 'HTML, CSS, JavaScript e APIs', 6), ('Tecnologia e Sistemas de Informação e de Comunicação, Segurança Cibernética e Crimes Digitais', 'Propriedades de segurança', 7), ('Tecnologia e Sistemas de Informação e de Comunicação, Segurança Cibernética e Crimes Digitais', 'Criptografia, auditoria e logs', 8), ('Tecnologia e Sistemas de Informação e de Comunicação, Segurança Cibernética e Crimes Digitais', 'Malware, ransomware e phishing', 9), ('Tecnologia e Sistemas de Informação e de Comunicação, Segurança Cibernética e Crimes Digitais', 'Crimes digitais e evidências digitais', 10), ('Tecnologia e Sistemas de Informação e de Comunicação, Segurança Cibernética e Crimes Digitais', 'LGPD e Marco Civil da Internet', 11)) as tp(disc, nome, ordem) on tp.disc = s.nome;

with t as (
  insert into public.contest_templates (slug, nome, tipo, plano, concurso, area, cargo, banca, salario, inscricao_valor, escolaridade, vagas, lotacao, etapas, etapas_tags, taf_itens, cor, origem, status, is_public, descricao, imagem_url, edital_url, prova_data, status_concurso, conteudo_provisorio, conteudo_fonte_url)
  values ('pcpr-papiloscopista-policial-2026', 'PCPR — Papiloscopista Policial 2026', 'concurso', 'PCPR — Papiloscopista Policial 2026', 'Polícia Civil do Paraná', 'Policial', 'Papiloscopista Policial', 'FGV', 'R$ 9.007,67', 'R$ 156,36', 'Curso superior completo', 'CR', 'Paraná', 'Prova objetiva, exame pré-admissional, TAF, avaliação psicológica, investigação social e prova de títulos', '["objetiva","titulos","taf","psicotecnico","investigacao_social","medico"]'::jsonb, '["Flexão de braços em barra fixa","Flexão abdominal remador","Shuttle Run","Escalada em corda","Corrida de resistência em 12 minutos"]'::jsonb, '#2563EB', 'catalogo', 'rascunho', false, 'Concurso da Polícia Civil do Paraná para Papiloscopista Policial, com prova objetiva e fases físicas, psicológicas e sociais.', NULL, 'https://conhecimento.fgv.br/sites/default/files/concursos/edital-01-2026-pcpr-publicacao.docx-1.pdf', '2026-10-11'::date, 'inscricoes_abertas', false, NULL)
  on conflict (slug) do nothing returning id
),
s as (
  insert into public.contest_template_subjects (template_id, nome, ordem)
  select t.id, d.nome, d.ordem from t cross join (values ('Língua Portuguesa', 0), ('Raciocínio Lógico-Matemático', 1), ('Ciências Forenses', 2)) as d(nome, ordem)
  returning id, nome
)
insert into public.contest_template_topics (subject_id, nome, ordem)
select s.id, tp.nome, tp.ordem from s join (values ('Língua Portuguesa', 'Compreensão e interpretação de textos', 0), ('Língua Portuguesa', 'Estrutura textual', 1), ('Língua Portuguesa', 'Coerência textual', 2), ('Língua Portuguesa', 'Organização do discurso', 3), ('Língua Portuguesa', 'Tipos textuais', 4), ('Língua Portuguesa', 'Textos literários e não literários', 5), ('Língua Portuguesa', 'Tipologia de frases', 6), ('Língua Portuguesa', 'Estrutura da oração', 7), ('Língua Portuguesa', 'Pontuação', 8), ('Língua Portuguesa', 'Sintaxe', 9), ('Língua Portuguesa', 'Ordem direta e inversa', 10), ('Língua Portuguesa', 'Registros de linguagem', 11), ('Raciocínio Lógico-Matemático', 'Lógica proposicional', 0), ('Raciocínio Lógico-Matemático', 'Conectivos e equivalências lógicas', 1), ('Raciocínio Lógico-Matemático', 'Teoria dos conjuntos', 2), ('Raciocínio Lógico-Matemático', 'Conjuntos numéricos', 3), ('Raciocínio Lógico-Matemático', 'Razões e proporções', 4), ('Raciocínio Lógico-Matemático', 'Grandezas e medidas', 5), ('Raciocínio Lógico-Matemático', 'Estruturas lógicas', 6), ('Raciocínio Lógico-Matemático', 'Tabelas e gráficos', 7), ('Raciocínio Lógico-Matemático', 'Análise combinatória', 8), ('Raciocínio Lógico-Matemático', 'Probabilidade', 9), ('Raciocínio Lógico-Matemático', 'Geometria', 10), ('Raciocínio Lógico-Matemático', 'Plano cartesiano', 11), ('Ciências Forenses', 'Medicina Legal', 0), ('Ciências Forenses', 'Antropologia Forense', 1), ('Ciências Forenses', 'Identificação humana', 2), ('Ciências Forenses', 'Papiloscopia', 3), ('Ciências Forenses', 'Identificação por DNA', 4), ('Ciências Forenses', 'Reconhecimento facial automatizado', 5), ('Ciências Forenses', 'Sexologia Forense', 6), ('Ciências Forenses', 'Traumatologia Forense', 7), ('Ciências Forenses', 'Balística forense', 8), ('Ciências Forenses', 'Tanatologia Forense', 9), ('Ciências Forenses', 'Toxicologia Forense', 10), ('Ciências Forenses', 'Documentoscopia e grafoscopia', 11), ('Ciências Forenses', 'Cadeia de custódia', 12)) as tp(disc, nome, ordem) on tp.disc = s.nome;
